camera:
  filters:
    hole_filling:
      enabled: false
    spatial:
      enabled: true
    temporal:
      enabled: true
  fps: 15
  resolution: 640x480
color_frame:
  stream_enabled: true
depth_frame:
  stream_enabled: true
image_size: 320
min_confidence: 0.85
network_tables:
  server: 10.59.87.2
  table: AdvantageKit/RealsenseVision
pipeline:
  args:
  - best_good_rknn_model
  type: DetectionDepthPipeline
rknn_chip_type: rk3588  # Options: rk3588, rk3588s, rk3576, rk3568, qcs6490
